"""followers

Revision ID: 0988964fc0d4
Revises: b04233863605
Create Date: 2020-08-16 19:03:10.799133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0988964fc0d4'
down_revision = 'b04233863605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
